workout.coefficients=0.50,0.6,0.65,0.55,0.50
workout.coefficient.pull_up=1
workout.coefficient.push_up=0.43
workout.coefficient.squat=0.31
workout.coefficient.abs=0.27
workout.increment-per-day=0.01

# Referral system configuration
referral.xp-per-referral=100