spring:
  application:
    name: SportBot
  cloud:
    gcp:
      sql:
        database-name: sportbotdb
        instance-connection-name: project-5a088b17-0e88-41b0-a00:europe-west1:sportbotdb
  datasource:
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  data:
    web:
      pageable:
        one-indexed-parameters: false

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

bot:
  name: SquatMasterBot
  token: ${TG_BOT_TOKEN}
  