--liquibase formatted sql

--changeset deniskaydunov:1
CREATE TABLE tags (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(50) NOT NULL UNIQUE,
    title   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE user_tags (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
     tag_id INT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
     assigned_at TIMESTAMP DEFAULT NOW(),
     UNIQUE(user_id, tag_id)
);