--liquibase formatted sql

--changeset deniskaydunov:1
CREATE TABLE ranks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(50) NOT NULL UNIQUE,
    title            VARCHAR(255) NOT NULL,
    exercise_type_id INTEGER NOT NULL REFERENCES exercise_types(id) ON DELETE CASCADE,
    threshold        INTEGER NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_ranks_exercise_type_threshold ON ranks(exercise_type_id, threshold);

CREATE TABLE user_ranks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rank_id     BIGINT NOT NULL REFERENCES ranks(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(user_id, rank_id)
);

INSERT INTO ranks (code, title, exercise_type_id, threshold, created_at) VALUES
     ('amoeba', 'Амеба', 2, 0, '2025-12-01 00:00:00'),
     ('infusorian', 'Инфузория', 2, 10, '2025-12-01 00:00:00'),
     ('larva', 'Личинка', 2, 25, '2025-12-01 00:00:00'),
     ('worm', 'Червь', 2, 50, '2025-12-01 00:00:00'),
     ('rag', 'Тряпка', 2, 100, '2025-12-01 00:00:00'),
     ('herbivore', 'Травоядное', 2, 250, '2025-12-01 00:00:00'),
     ('pitiful_mammal', 'Жалкое млекопитающее', 2, 500, '2025-12-01 00:00:00'),
     ('skinny_guy', 'Дрыщ', 2, 1000, '2025-12-01 00:00:00'),
     ('young_lad', 'Пацан', 2, 1507, '2025-12-01 00:00:00'),
     ('gym_student', 'Студент качалки', 2, 2176, '2025-12-01 00:00:00'),
     ('man', 'Мужик', 2, 3033, '2025-12-01 00:00:00'),
     ('jock_lifter', 'Качок', 2, 4107, '2025-12-01 00:00:00'),
     ('bodybuilder', 'Билдер', 2, 5428, '2025-12-01 00:00:00'),
     ('powerlifter', 'Лифтер', 2, 7027, '2025-12-01 00:00:00'),
     ('alpha_male', 'Самец', 2, 8937, '2025-12-01 00:00:00'),
     ('beast', 'Животное', 2, 11190, '2025-12-01 00:00:00'),
     ('alpha', 'Альфа', 2, 13822, '2025-12-01 00:00:00'),
     ('john_wick', 'Джон Уик', 2, 16867, '2025-12-01 00:00:00'),
     ('predator', 'Хищник', 2, 20364, '2025-12-01 00:00:00'),
     ('sigma_male', 'Сигмабой', 2, 24349, '2025-12-01 00:00:00'),
     ('mutant', 'Мутант', 2, 28860, '2025-12-01 00:00:00'),
     ('hulk', 'Халк', 2, 33938, '2025-12-01 00:00:00'),
     ('machine', 'Машина', 2, 39624, '2025-12-01 00:00:00'),
     ('terminator', 'Терминатор', 2, 45957, '2025-12-01 00:00:00'),
     ('biorobot', 'Биоробот', 2, 52981, '2025-12-01 00:00:00'),
     ('calisthenics_master', 'Повелитель турников', 2, 60739, '2025-12-01 00:00:00'),
     ('bar_destroyer', 'Разрушитель турников', 2, 69275, '2025-12-01 00:00:00'),
     ('super_organism', 'Сверхсущество', 2, 78633, '2025-12-01 00:00:00'),
     ('god', 'Бог', 2, 88859, '2025-12-01 00:00:00'),
     ('what_are_you_creature', 'Кто ты, тварь?!', 2, 100000, '2025-12-01 00:00:00');
