--liquibase formatted sql

--changeset deniskaydunov:25
-- Add English translations for Russian push-up motivations
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
-- General motivational messages
(1, 'You haven''t lost until you''ve given up.', 'en'),
(1, 'Every rep is a step towards a better version of yourself.', 'en'),
(1, 'Real growth begins beyond your comfort zone.', 'en'),
(1, 'Yesterday you dreamed of this. Today you''ve already started.', 'en'),
(1, 'Your body can do more than your mind says.', 'en'),
(1, 'Patience and effort are the keys to strength.', 'en'),
(1, 'Don''t look for excuses - find a way.', 'en'),
(1, 'Small steps every day make a big difference.', 'en'),
(1, 'If you want results - start with discipline.', 'en'),
(1, 'Do today what others won''t - tomorrow you''ll be where they can''t.', 'en'),
(1, 'Victory comes to those who keep going.', 'en'),
(1, 'Every drop of sweat is a step forward.', 'en'),
(1, 'The strong one isn''t who never falls, but who gets up again and again.', 'en'),
(1, 'It doesn''t matter how slowly you go - you''re still ahead of those who didn''t start.', 'en'),
(1, 'While others wait for inspiration, you train.', 'en'),
(1, 'You''ve already taken the first step - now just don''t stop.', 'en'),
(1, 'Motivation leads to the start. Habit leads to results.', 'en'),
(1, 'You''re stronger than you think.', 'en'),
(1, 'Don''t compare yourself to others - compare to yesterday''s you.', 'en'),
(1, 'The secret to progress is not stopping.', 'en'),

-- Technique tips
(1, 'Keep your body straight - from head to toe.', 'en'),
(1, 'Don''t raise your hips too high and don''t sag your back.', 'en'),
(1, 'Look at the floor, don''t lift your head.', 'en'),
(1, 'Lower yourself until your chest almost touches the floor.', 'en'),
(1, 'Elbows should go at a 45° angle to your body, not to the sides.', 'en'),
(1, 'Maintain core tension - don''t relax your abs.', 'en'),
(1, 'Don''t rush - do the movement smoothly and under control.', 'en'),
(1, 'Breathe in on the way down, breathe out on the way up.', 'en'),
(1, 'Warm up before training to avoid injuries.', 'en'),
(1, 'Make sure your wrists are under your shoulders.', 'en'),
(1, 'Place your palms firmly, fingers slightly spread.', 'en'),
(1, 'Don''t drop yourself down - control the downward movement.', 'en'),
(1, 'Don''t hold your breath during push-ups - it reduces endurance.', 'en'),
(1, 'Strengthen your core muscles - it will improve stability.', 'en'),
(1, 'If it''s hard - start from your knees, but maintain proper form.', 'en'),
(1, 'Don''t do "bouncy" push-ups - better fewer, but quality.', 'en'),
(1, 'Don''t push forward with your hands - movement is strictly vertical.', 'en'),
(1, 'After training, stretch your chest and shoulder muscles.', 'en'),
(1, 'Use a mirror or video to track your form.', 'en'),
(1, 'Quality over quantity - proper technique gives better results.', 'en'),

-- Motivational and humorous
(1, '🔥 What do I hear? "I ate", "I''m dead", "I''ll join tomorrow"? You''re not on vacation, you''re in a challenge! Everyone who''s slacking now should know - while you''re resting, someone''s getting stronger. 🍗 Full? Push up so it doesn''t stick! 💀 Dead? Rise from the floor! 📆 Tomorrow? There''s no "tomorrow", there''s today. 10 minutes. One set. No excuses. Go!🔥', 'en'),
(1, 'Try to lower your chest lower. No higher than 10 cm from the floor.', 'en'),
(1, 'Your opponent is yourself, defeat your laziness.', 'en'),
(1, 'Don''t rush, don''t compete, the main thing is your personal progress over yourself.', 'en'),
(1, 'Someone looks at the leaderboard, and someone makes results.', 'en'),
(1, 'Push-ups aren''t just an exercise, they''re a way to tell your body: Today I''m the boss, not the couch!', 'en'),
(1, 'Do today what others won''t - tomorrow you''ll be where they can''t.', 'en'),
(1, 'Push-ups are like life: first it''s hard, then it''s hard, but at least the muscles are beautiful! 💪😄', 'en'),
(1, 'While someone''s busy, others push the floor and become sigma males! 😆', 'en'),
(1, 'Every rep is an investment in your fitness, endurance and confidence.', 'en'),
(1, 'Push the floor! And let the earth feel that you''re awake.', 'en'),
(1, 'Keep going and you''ll become the hero of your own fitness blockbuster!', 'en'),
(1, 'With push-ups you''re not just working chest and triceps - but also willpower. And that''s the most powerful weapon.', 'en'),
(1, 'The winner isn''t who does more, but who does it regularly.', 'en'),
(1, 'Every press of the set button isn''t just a number. It''s +1 to your body, +1 to discipline, +1 to self-respect.', 'en'),
(1, 'Do today what others won''t - tomorrow you''ll be where they can''t.', 'en'),
(1, 'Now go, do your thing. And if the world tries to drop you again - drop it back.', 'en'),
(1, 'Victory comes to those who keep going.', 'en'),
(1, 'If you''re tired of push-ups, remember that the world is also tired of you, but doesn''t let you rest. Time to move forward.', 'en'),
(1, 'Push-ups don''t ask if you''re ready, they''ll just let you down if you''re too weak. There''s your motivation.', 'en'),
(1, 'If you can''t do 20 push-ups, your arms are about as useful as your excuses.', 'en'),
(1, 'Push up so your muscles understand: dying is normal, but giving up is a sin.', 'en'),
(1, 'Push-up technique is simple: you go down - you realize life''s pain.', 'en'),
(1, 'Technique is simple: fell - got up, but sometimes falling is already an achievement.', 'en'),
(1, 'Push up until your chest says: "Goodbye, brain"', 'en'),
(1, 'Technique? Just don''t fall face-first on the floor - that''s already success!', 'en'),
(1, 'If push-ups don''t kill you, you''re doing them wrong. Or too few.', 'en'),
(1, 'Use a program, that way you''ll achieve better results.', 'en'),
(1, 'Push-ups aren''t just a workout, they''re an investment in your energy for conquering new horizons.', 'en'),
(1, 'Every push-up is a step towards becoming better than you were yesterday.', 'en'),
(1, 'Physical fitness is like a startup: it requires persistence and consistency to succeed.', 'en'),
(1, 'When you do push-ups, you learn to overcome limits. That''s what makes us human.', 'en'),
(1, 'The body is a tool. Push-ups help tune it for great achievements.', 'en'),
(1, 'Studying physical loads, you discover new possibilities both in life and in business.', 'en'),
(1, 'Push-up challenges are like career challenges: only by overcoming them do you grow.', 'en'),
(1, 'Physical fitness is the foundation on which success in any endeavor is built.', 'en'),
(1, 'Every push-up is a reminder that perseverance and hard work are always rewarded.', 'en'),
(1, 'To change the world, start with yourself. Push-ups are a small step towards global vision.', 'en'),
(1, 'Push-ups aren''t just physical effort, but meditation in motion, where every drop of sweat cleanses the soul. (c) Buddha', 'en'),
(1, 'With each push-up you not only strengthen your body, but also free your spirit from the shackles of doubt. (c) Buddha', 'en'),
(1, 'Don''t fear falls, for in every fall lies the opportunity to rise stronger. (c) Buddha', 'en'),
(1, 'Your body is a temple, and every push-up is a step towards its perfection. (c) Buddha', 'en'),
(1, 'When you do push-ups, you''re not just training muscles, you''re training your will. (c) Buddha', 'en'),
(1, 'Every effort is an opportunity to connect with yourself and become closer to your true self. (c) Buddha', 'en'),
(1, 'Push-ups are a dialogue with your own body, where you learn to listen and understand it. (c) Buddha', 'en'),
(1, 'In every rep there''s a chance to overcome not only physical boundaries, but also inner fears. (c) Buddha', 'en'),
(1, 'Doing push-ups, you''re not just moving up - you''re rising towards your dream. (c) Buddha', 'en'),
(1, 'Strength isn''t in how many times you push up, but in how you transform each movement into a step towards self-awareness. (c) Buddha', 'en'),
(1, 'Rest time is over - push the floor!', 'en'),
(1, 'If the training program became too hard - go to your profile and update your max.', 'en'),
(1, 'You didn''t slip - you stumbled. And then got up, wiped the mayo off your chin and went to do push-ups like a warrior!', 'en'),
(1, 'The floor is your training partner - respect it!', 'en'),
(1, 'Push-ups teach you that limits exist only in your head.', 'en'),
(1, 'Every workout brings you closer to your goals.', 'en'),
(1, 'Champions aren''t born - they''re made through push-ups.', 'en'),
(1, 'Your muscles remember every rep - make them count.', 'en'),
(1, 'Push the floor like you''re pushing away your doubts.', 'en'),
(1, 'Consistency beats intensity - train regularly!', 'en');

--changeset deniskaydunov:26
-- Add Ukrainian translations for Russian push-up motivations
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
-- Загальні мотиваційні повідомлення
(1, 'Ти не програв, поки не здався.', 'uk'),
(1, 'Кожне повторення — крок до кращої версії себе.', 'uk'),
(1, 'Справжнє зростання починається за межами комфорту.', 'uk'),
(1, 'Вчора ти мріяв про це. Сьогодні ти вже почав.', 'uk'),
(1, 'Твоє тіло може більше, ніж говорить розум.', 'uk'),
(1, 'Терпіння і зусилля — ключі до сили.', 'uk'),
(1, 'Не шукай виправдань — шукай шлях.', 'uk'),
(1, 'Маленькі кроки кожен день роблять велику справу.', 'uk'),
(1, 'Якщо ти хочеш результат — почни з дисципліни.', 'uk'),
(1, 'Зроби сьогодні те, що інші не хочуть — завтра ти будеш там, де вони не зможуть.', 'uk'),
(1, 'Перемога приходить до тих, хто продовжує.', 'uk'),
(1, 'Кожна крапля поту — це крок вперед.', 'uk'),
(1, 'Сильний не той, хто ніколи не падає, а той, хто піднімається знову і знову.', 'uk'),
(1, 'Неважливо, наскільки повільно ти йдеш — ти все одно випереджаєш тих, хто не почав.', 'uk'),
(1, 'Поки інші чекають натхнення, ти тренуєшся.', 'uk'),
(1, 'Ти вже зробив перший крок — тепер просто не зупиняйся.', 'uk'),
(1, 'Мотивація приводить до початку. Звичка веде до результату.', 'uk'),
(1, 'Ти сильніший, ніж тобі здається.', 'uk'),
(1, 'Не порівнюй себе з іншими — порівнюй з собою вчорашнім.', 'uk'),
(1, 'Секрет прогресу — не зупинятися.', 'uk'),

-- Поради щодо техніки
(1, 'Тримай тіло прямим — від голови до п''ят.', 'uk'),
(1, 'Не піднімай таз занадто високо і не провалюй спину.', 'uk'),
(1, 'Дивись в підлогу, не задирай голову.', 'uk'),
(1, 'Опускайся до рівня, коли груди майже торкаються підлоги.', 'uk'),
(1, 'Лікті мають йти під кутом 45° до тіла, а не в сторони.', 'uk'),
(1, 'Зберігай напругу в корпусі — не розслабляй живіт.', 'uk'),
(1, 'Не поспішай — роби рух плавно і під контролем.', 'uk'),
(1, 'На вдих — вниз, на видих — вгору.', 'uk'),
(1, 'Розігрівайся перед тренуванням, щоб уникнути травм.', 'uk'),
(1, 'Стеж за тим, щоб кисті були під плечима.', 'uk'),
(1, 'Ставь долоні щільно, пальці злегка розведені.', 'uk'),
(1, 'Не кидай себе вниз — контролюй рух донизу.', 'uk'),
(1, 'Під час віджимань не забувай дихати — затримка дихання знижує витривалість.', 'uk'),
(1, 'Зміцнюй м''язи кора — це покращить стабільність.', 'uk'),
(1, 'Якщо важко — почни з колін, але дотримуйся техніки.', 'uk'),
(1, 'Не роби «човникові» віджимання — краще менше, але якісно.', 'uk'),
(1, 'Руками не штовхайся вперед — рух строго вертикально.', 'uk'),
(1, 'Після тренування зроби розтяжку грудних і плечових м''язів.', 'uk'),
(1, 'Використовуй дзеркало або відео, щоб відстежувати форму.', 'uk'),
(1, 'Якість важливіша за кількість — правильна техніка дає кращий результат.', 'uk'),

-- Мотиваційні та жартівливі
(1, '🔥 Що я чую? «Я поїв», «я вмер», «завтра підключусь»? Ви не на курорті, ви в челенджі! Кожен, хто зараз ледарює, нехай знає — поки ти відпочиваєш, хтось стає сильнішим. 🍗 Наївся? Віджимайся, щоб не відкладалося. 💀 Помер? Воскресай від підлоги! 📆 Завтра? Немає «завтра», є сьогодні. 10 хвилин. Один підхід. Без відмазок. Вперед!🔥', 'uk'),
(1, 'Намагайся груди опускати нижче. Не вище 10 см від підлоги.', 'uk'),
(1, 'Твій суперник ти сам, перемож свою лінь.', 'uk'),
(1, 'Не поспішай, не змагайся, головне це твій особистий прогрес над самим собою.', 'uk'),
(1, 'Хтось дивиться таблицю лідерів, а хтось робить результат.', 'uk'),
(1, 'Віджимання — це не просто вправа, а спосіб сказати тілу: Сьогодні я господар, а не диван!', 'uk'),
(1, 'Зроби сьогодні те, що інші не хочуть — завтра ти будеш там, де вони не зможуть.', 'uk'),
(1, 'Віджимання — це як життя: спочатку важко, потім важко, але зате м''язи гарні! 💪😄', 'uk'),
(1, 'Поки хтось зайнятий, інші жмуть підлогу і стають сігма-хлопцями! 😆', 'uk'),
(1, 'Кожне повторення — це внесок у твою форму, витривалість і впевненість.', 'uk'),
(1, 'Тисни підлогу! І нехай земля відчує, що ти прокинувся.', 'uk'),
(1, 'Продовжуй і станеш героєм свого власного фітнес-блокбастера!', 'uk'),
(1, 'З віджиманнями ти прокачуєш не тільки грудні та тріцепси — а й силу волі. А це — найпотужніша зброя.', 'uk'),
(1, 'Перемагає не той, хто робить більше, а той, хто робить регулярно.', 'uk'),
(1, 'Кожне натискання на кнопку підходу — це не просто цифра. Це +1 до твого тіла, +1 до дисципліни, +1 до поваги до самого себе.', 'uk'),
(1, 'Зроби сьогодні те, що інші не хочуть — завтра ти будеш там, де вони не зможуть.', 'uk'),
(1, 'Тепер іди, роби свою справу. І якщо світ знову спробує впустити тебе — впусти його у відповідь.', 'uk'),
(1, 'Перемога приходить до тих, хто продовжує.', 'uk'),
(1, 'Якщо втомився віджиматися, згадай, що світ теж втомився від тебе, але не дає тобі відпочивати. Пора рухатися вперед.', 'uk'),
(1, 'Віджимання не запитують, готовий ти чи ні, вони просто відпустять тебе вниз, якщо ти занадто слабкий. Ось тобі і мотивація.', 'uk'),
(1, 'Якщо ти не можеш зробити 20 віджимань, значить твої руки приблизно так само корисні, як і твої виправдання.', 'uk'),
(1, 'Віджимайся так, щоб твої м''язи зрозуміли: вмерти — це норма, але здаватися — гріх.', 'uk'),
(1, 'Техніка віджимань проста: опускаєшся — усвідомлюєш біль життя.', 'uk'),
(1, 'Техніка проста: впав — встав, але іноді й впасти — вже досягнення.', 'uk'),
(1, 'Віджимайся, поки груди не скажуть: "Прощавай, мозок"', 'uk'),
(1, 'Техніка? Просто не падай обличчям в підлогу — це вже успіх!', 'uk'),
(1, 'Якщо віджимання не вбивають, значить ти робиш їх неправильно. Або занадто мало.', 'uk'),
(1, 'Використовуй програму, так ти досягнеш більшого результату.', 'uk'),
(1, 'Віджимання — це не просто тренування, це інвестиція в твою енергію для підкорення нових горизонтів.', 'uk'),
(1, 'Кожне віджимання — це крок до того, щоб стати кращим, ніж ти був вчора.', 'uk'),
(1, 'Фізична форма — це як стартап: потрібна наполегливість і постійність, щоб досягти успіху.', 'uk'),
(1, 'Коли ти віджимаєшся, ти вчишся долати межі. Це те, що робить нас людьми.', 'uk'),
(1, 'Тіло — це інструмент. Віджимання допомагають налаштувати його для великих звершень.', 'uk'),
(1, 'Вивчаючи фізичні навантаження, ти відкриваєш нові можливості як у житті, так і в бізнесі.', 'uk'),
(1, 'Складнощі віджимань — це як виклики в кар''єрі: тільки долаючи їх, ти ростеш.', 'uk'),
(1, 'Фізична форма — це основа, на якій будується успіх у будь-якому починанні.', 'uk'),
(1, 'Кожне віджимання — це нагадування, що наполегливість і працьовитість завжди винагороджуються.', 'uk'),
(1, 'Щоб змінити світ, почни з себе. Віджимання — це маленький крок до глобального бачення.', 'uk'),
(1, 'Віджимання — це не просто фізичне зусилля, а медитація в русі, де кожна крапля поту очищає душу. (з) Будда', 'uk'),
(1, 'З кожним віджиманням ти не тільки зміцнюєш тіло, а й звільняєш дух від оків сумнівів. (з) Будда', 'uk'),
(1, 'Не бійся падінь, адже в кожному падінні прихована можливість піднятися сильнішим. (з) Будда', 'uk'),
(1, 'Твоє тіло — це храм, і кожне віджимання — це крок до його досконалості. (з) Будда', 'uk'),
(1, 'Коли ти віджимаєшся, ти не просто тренуєш м''язи, ти тренуєш свою волю. (з) Будда', 'uk'),
(1, 'Кожне зусилля — це можливість з''єднатися з собою і стати ближче до свого справжнього я. (з) Будда', 'uk'),
(1, 'Віджимання — це діалог з власним тілом, де ти вчишся слухати і розуміти його. (з) Будда', 'uk'),
(1, 'У кожному повторенні є шанс подолати не тільки фізичні межі, а й внутрішні страхи. (з) Будда', 'uk'),
(1, 'Віджимаючись, ти не просто рухаєшся вгору — ти піднімаєшся до своєї мрії. (з) Будда', 'uk'),
(1, 'Сила не в тому, скільки разів ти віджимаєшся, а в тому, як ти трансформуєш кожен рух у крок до самопізнання. (з) Будда', 'uk'),
(1, 'Час відпочинку вийшов - жми підлогу!', 'uk'),
(1, 'Якщо програма тренування стала дуже важкою - зайди в профіль і оновіть свій максимум.', 'uk'),
(1, 'Ти не скотився — ти спіткнувся. А потім встав, витер майонез з підборіддя і пішов віджиматися як воїн!', 'uk'),
(1, 'Підлога — твій тренувальний партнер — поважай її!', 'uk'),
(1, 'Віджимання вчать тебе, що межі існують лише у твоїй голові.', 'uk'),
(1, 'Кожне тренування наближає тебе до твоїх цілей.', 'uk'),
(1, 'Чемпіони не народжуються — вони створюються через віджимання.', 'uk'),
(1, 'Твої м''язи пам''ятають кожне повторення — роби їх значущими.', 'uk'),
(1, 'Тисни підлогу, наче відштовхуєш свої сумніви.', 'uk'),
(1, 'Постійність перемагає інтенсивність — тренуйся регулярно!', 'uk');

--changeset deniskaydunov:27
-- Add English translations for Russian pull-up motivations
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(2, 'Every pull-up is a step up not only in body but also in spirit.', 'en'),
(2, 'Weak arms? Perfect, pull-ups are made to make them strong.', 'en'),
(2, 'Pull-ups make you not just strong - but a true warrior.', 'en'),
(2, 'Hard? That means you''re on the right path.', 'en'),
(2, 'Every pull-up is a brick in your fortress of strength.', 'en'),
(2, 'Don''t let go of the bar first - let your laziness give up first.', 'en'),
(2, 'Pull-ups teach: falling is easy, rising is an art.', 'en'),
(2, 'Your body grows not when it''s easy, but when it''s hard.', 'en'),
(2, 'Pull up until those who laughed start to envy.', 'en'),
(2, 'It doesn''t matter how many times you slipped - what matters is how many times you grabbed the bar again.', 'en'),
(2, 'Pull-ups are a conversation with yourself: "You can do it!" - "Prove it!".', 'en');

--changeset deniskaydunov:28
-- Add Ukrainian translations for Russian pull-up motivations
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(2, 'Кожне підтягування — це крок вгору не тільки тілом, а й духом.', 'uk'),
(2, 'Слабкі руки? Чудово, підтягування створені для їхньої сили.', 'uk'),
(2, 'Підтягування роблять з тебе не просто сильного — а справжнього воїна.', 'uk'),
(2, 'Важко? Значить, ти на правильному шляху.', 'uk'),
(2, 'Кожне підтягування — цеглинка у твою фортецю сили.', 'uk'),
(2, 'Не відпускай перекладину першим — спочатку нехай здасться твоя лінь.', 'uk'),
(2, 'Підтягування вчать: падати легко, піднімати — мистецтво.', 'uk'),
(2, 'Твоє тіло росте не тоді, коли легко, а коли складно.', 'uk'),
(2, 'Підтягуйся, поки ті, хто сміявся, не почнуть заздрити.', 'uk'),
(2, 'Не важливо, скільки разів ти зірвався — важливо, скільки разів знову схопився за перекладину.', 'uk'),
(2, 'Підтягування — це розмова з собою: «Ти можеш!» — «Доведи!».', 'uk');

--changeset deniskaydunov:29
-- Add English translations for Russian squat motivations
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(3, 'Every squat brings you closer to perfect form!', 'en'),
(3, 'Strong glutes - not a dream, but a goal!', 'en'),
(3, 'A girl with squats is a girl with character!', 'en'),
(3, 'You squat - you win!', 'en'),
(3, 'Laziness doesn''t build glutes. Squat!', 'en'),
(3, 'Results are built step by step, squat by squat.', 'en'),
(3, 'Your ideal legs are already close, just don''t stop.', 'en'),
(3, 'Do it for yourself, your beauty and confidence.', 'en'),
(3, 'No one will regret a workout - only missing it.', 'en'),
(3, 'Squat like you''re looking in the mirror of your dreams!', 'en'),
(3, 'A firm booty is the best outfit.', 'en'),
(3, 'You can do more than you think.', 'en'),
(3, 'Beauty requires movement, not sacrifice.', 'en'),
(3, 'Even 5 minutes a day brings you closer to your dream body.', 'en'),
(3, 'Today''s efforts - tomorrow''s pride.', 'en'),
(3, 'Squats are your path to confidence.', 'en'),
(3, 'You already have everything to become better.', 'en'),
(3, 'Strong legs - confident steps through life.', 'en'),
(3, 'Squat not for someone - for yourself!', 'en'),
(3, 'Your booty will thank you!', 'en'),

-- Technique tips
(3, 'Knees don''t go past your toes!', 'en'),
(3, 'Keep your back straight - like you''re carrying a book.', 'en'),
(3, 'Don''t lift your heels off the floor.', 'en'),
(3, 'Deep squat - quality squat.', 'en'),
(3, 'Breathe: down - inhale, up - exhale.', 'en'),
(3, 'Legs work, not your lower back.', 'en'),
(3, 'Look forward, not at the floor.', 'en'),
(3, 'Squeeze your glutes on the way up.', 'en'),
(3, 'Direct your knees along the line of your toes.', 'en'),
(3, 'Don''t rush - feel every movement.', 'en'),
(3, 'Arms forward - for balance.', 'en'),
(3, 'Keep your abs engaged.', 'en'),
(3, 'Don''t arch your lower back.', 'en'),
(3, 'Squat to parallel with the floor - at minimum.', 'en'),
(3, 'Control the movement, don''t drop down.', 'en'),
(3, 'Don''t lean back when going up.', 'en'),
(3, 'Direction - strictly up, not diagonally.', 'en'),
(3, 'Weight on your heels, not on your toes.', 'en'),
(3, 'Shoulder blades together, chest slightly forward.', 'en'),
(3, 'Do less, but with quality!', 'en'),
(3, 'Not a booty but a nut. Squirrels start to notice you.', 'en'),
(3, 'Want glutes like a tigress? Then do squats!', 'en'),
(3, 'Squats = Bali', 'en'),
(3, 'Squat like your exes saw you - let your booty speak louder than words!', 'en');

--changeset deniskaydunov:30
-- Add Ukrainian translations for Russian squat motivations
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(3, 'Кожне присідання наближає тебе до ідеальної форми!', 'uk'),
(3, 'Міцні сідниці — це не мрія, а мета!', 'uk'),
(3, 'Дівчина з присіданнями — дівчина з характером!', 'uk'),
(3, 'Присідаєш — перемагаєш!', 'uk'),
(3, 'Лінь не качає попу. Присідай!', 'uk'),
(3, 'Результат будується крок за кроком, присід за присідом.', 'uk'),
(3, 'Твої ідеальні ноги вже поруч, просто не зупиняйся.', 'uk'),
(3, 'Зроби це для себе, своєї краси і впевненості.', 'uk'),
(3, 'Ніхто не пошкодує про тренування — тільки про те, що пропустив його.', 'uk'),
(3, 'Присідай, наче дивишся в дзеркало мрії!', 'uk'),
(3, 'Пружна попа — найкращий наряд.', 'uk'),
(3, 'Ти можеш більше, ніж думаєш.', 'uk'),
(3, 'Краса вимагає руху, а не жертв.', 'uk'),
(3, 'Навіть 5 хвилин на день наближають до фігури мрії.', 'uk'),
(3, 'Сьогоднішні зусилля — завтрашня гордість.', 'uk'),
(3, 'Присідання — твій шлях до впевненості.', 'uk'),
(3, 'У тебе вже є все, щоб стати кращою.', 'uk'),
(3, 'Сильні ноги — впевнені кроки по життю.', 'uk'),
(3, 'Присідай не заради когось — заради себе!', 'uk'),
(3, 'Твоя попа скаже тобі спасибі!', 'uk'),

-- Поради щодо техніки
(3, 'Коліна не виходять за носки!', 'uk'),
(3, 'Тримай спину рівно — наче книжку несеш.', 'uk'),
(3, 'П''яти не відриваєш від підлоги.', 'uk'),
(3, 'Глибокий присід — якісний присід.', 'uk'),
(3, 'Дихай: вниз — вдих, вгору — видих.', 'uk'),
(3, 'Працюють ноги, а не поперек.', 'uk'),
(3, 'Дивись вперед, не в підлогу.', 'uk'),
(3, 'Напружуй сідниці при підйомі.', 'uk'),
(3, 'Коліна направляй по лінії носків.', 'uk'),
(3, 'Не поспішай — відчувай кожен рух.', 'uk'),
(3, 'Руки вперед — для балансу.', 'uk'),
(3, 'Живіт тримай в тонусі.', 'uk'),
(3, 'Не прогинай спину в попереку.', 'uk'),
(3, 'Присідай до паралелі з підлогою — мінімум.', 'uk'),
(3, 'Контролюй рух, не падай вниз.', 'uk'),
(3, 'Не відкидайся назад при підйомі.', 'uk'),
(3, 'Напрямок — строго вгору, не по діагоналі.', 'uk'),
(3, 'Вага — на п''ятах, не на носках.', 'uk'),
(3, 'Лопатки зведені, груди злегка вперед.', 'uk'),
(3, 'Роби менше, але якісно!', 'uk'),
(3, 'Не попа а горіх. Білки починають поглядати за тобою.', 'uk'),
(3, 'Хочеш сідниці як у тигриці? Тоді роби присідання!', 'uk'),
(3, 'Присідання = Балі', 'uk'),
(3, 'Присідай, наче тебе побачили твої колишні — нехай дупа говорить гучніше за слова!', 'uk');

--changeset deniskaydunov:31
-- Add abs motivations in Russian
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(4, 'Крепкий пресс — основа сильного тела!', 'ru'),
(4, 'Каждое скручивание делает твой пресс сильнее.', 'ru'),
(4, 'Пресс не качается случайно — только упорством.', 'ru'),
(4, 'Кубики пресса — это дело времени и дисциплины.', 'ru'),
(4, 'Твой пресс скажет тебе спасибо за каждое повторение.', 'ru'),
(4, 'Сильный кор — залог хорошей осанки.', 'ru'),
(4, 'Работай над прессом сегодня, гордись им завтра.', 'ru'),
(4, 'Не останавливайся — твой пресс уже на пути к совершенству.', 'ru'),
(4, 'Пресс — это не только красиво, но и функционально.', 'ru'),
(4, 'Делай пресс регулярно — результат не заставит себя ждать.', 'ru'),
(4, 'Чувствуй жжение — это работают твои мышцы.', 'ru'),
(4, 'Пресс качается на кухне и в зале.', 'ru'),
(4, 'Каждый подход — шаг к рельефному прессу.', 'ru'),
(4, 'Твой корпус — твоя сила, укрепляй его.', 'ru'),
(4, 'Не ищи оправданий — качай пресс!', 'ru'),
(4, 'Сильный пресс — уверенная походка.', 'ru'),
(4, 'Пресс не терпит лени — только действие.', 'ru'),
(4, 'Работай над прессом — работай над собой.', 'ru'),
(4, 'Крепкий кор защищает позвоночник.', 'ru'),
(4, 'Качай пресс с умом — техника важнее количества.', 'ru'),
(4, 'Не прогибай поясницу — работает пресс, не спина.', 'ru'),
(4, 'Подбородок к груди, взгляд в потолок.', 'ru'),
(4, 'Выдох на усилии — вдох при расслаблении.', 'ru'),
(4, 'Не тяни шею руками — работай прессом.', 'ru'),
(4, 'Медленные повторения эффективнее быстрых.', 'ru'),
(4, 'Напрягай пресс в верхней точке.', 'ru'),
(4, 'Не отрывай поясницу от пола при скручиваниях.', 'ru'),
(4, 'Чувствуй каждое сокращение мышц пресса.', 'ru'),
(4, 'Делай планку — это основа сильного кора.', 'ru'),
(4, 'Разнообразие упражнений — ключ к прогрессу.', 'ru');

--changeset deniskaydunov:32
-- Add abs motivations in English
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(4, 'Strong abs - the foundation of a strong body!', 'en'),
(4, 'Every crunch makes your abs stronger.', 'en'),
(4, 'Abs don''t happen by accident - only through persistence.', 'en'),
(4, 'Six-pack abs are a matter of time and discipline.', 'en'),
(4, 'Your abs will thank you for every rep.', 'en'),
(4, 'Strong core - the key to good posture.', 'en'),
(4, 'Work on your abs today, be proud tomorrow.', 'en'),
(4, 'Don''t stop - your abs are already on the path to perfection.', 'en'),
(4, 'Abs aren''t just beautiful, they''re functional.', 'en'),
(4, 'Train your abs regularly - results won''t keep you waiting.', 'en'),
(4, 'Feel the burn - that''s your muscles working.', 'en'),
(4, 'Abs are made in the kitchen and the gym.', 'en'),
(4, 'Every set is a step towards defined abs.', 'en'),
(4, 'Your core is your strength, strengthen it.', 'en'),
(4, 'Don''t look for excuses - train your abs!', 'en'),
(4, 'Strong abs - confident posture.', 'en'),
(4, 'Abs don''t tolerate laziness - only action.', 'en'),
(4, 'Work on your abs - work on yourself.', 'en'),
(4, 'Strong core protects your spine.', 'en'),
(4, 'Train abs smartly - technique over quantity.', 'en'),
(4, 'Don''t arch your lower back - abs work, not spine.', 'en'),
(4, 'Chin to chest, eyes to ceiling.', 'en'),
(4, 'Exhale on effort - inhale on relaxation.', 'en'),
(4, 'Don''t pull your neck with hands - work with abs.', 'en'),
(4, 'Slow reps are more effective than fast ones.', 'en'),
(4, 'Squeeze your abs at the top position.', 'en'),
(4, 'Don''t lift your lower back off the floor during crunches.', 'en'),
(4, 'Feel every contraction of your ab muscles.', 'en'),
(4, 'Do planks - it''s the foundation of a strong core.', 'en'),
(4, 'Variety of exercises - the key to progress.', 'en');

--changeset deniskaydunov:33
-- Add abs motivations in Ukrainian
INSERT INTO motivation (exercise_type_id, message, locale) VALUES
(4, 'Міцний прес — основа сильного тіла!', 'uk'),
(4, 'Кожне скручування робить твій прес сильнішим.', 'uk'),
(4, 'Прес не качається випадково — тільки наполегливістю.', 'uk'),
(4, 'Кубики преса — це справа часу і дисципліни.', 'uk'),
(4, 'Твій прес скаже тобі спасибі за кожне повторення.', 'uk'),
(4, 'Сильний кор — запорука гарної постави.', 'uk'),
(4, 'Працюй над пресом сьогодні, пишайся ним завтра.', 'uk'),
(4, 'Не зупиняйся — твій прес вже на шляху до досконалості.', 'uk'),
(4, 'Прес — це не тільки красиво, а й функціонально.', 'uk'),
(4, 'Роби прес регулярно — результат не змусить себе чекати.', 'uk'),
(4, 'Відчувай печіння — це працюють твої м''язи.', 'uk'),
(4, 'Прес качається на кухні і в залі.', 'uk'),
(4, 'Кожен підхід — крок до рельєфного преса.', 'uk'),
(4, 'Твій корпус — твоя сила, зміцнюй його.', 'uk'),
(4, 'Не шукай виправдань — качай прес!', 'uk'),
(4, 'Сильний прес — впевнена хода.', 'uk'),
(4, 'Прес не терпить ліні — тільки дія.', 'uk'),
(4, 'Працюй над пресом — працюй над собою.', 'uk'),
(4, 'Міцний кор захищає хребет.', 'uk'),
(4, 'Качай прес з розумом — техніка важливіша за кількість.', 'uk'),
(4, 'Не прогинай поперек — працює прес, не спина.', 'uk'),
(4, 'Підборіддя до грудей, погляд у стелю.', 'uk'),
(4, 'Видих на зусиллі — вдих при розслабленні.', 'uk'),
(4, 'Не тягни шию руками — працюй пресом.', 'uk'),
(4, 'Повільні повторення ефективніші за швидкі.', 'uk'),
(4, 'Напружуй прес у верхній точці.', 'uk'),
(4, 'Не відривай поперек від підлоги при скручуваннях.', 'uk'),
(4, 'Відчувай кожне скорочення м''язів преса.', 'uk'),
(4, 'Роби планку — це основа сильного кора.', 'uk'),
(4, 'Різноманітність вправ — ключ до прогресу.', 'uk');
