spring:
  application:
    name: SportBot
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  cloud:
    gcp:
      sql:
        enabled: false